# Generated by Django 3.0.6 on 2020-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('identity', models.CharField(max_length=20)),
                ('phonenum', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
