# Generated by Django 3.0.7 on 2020-06-21 07:54

from django.db import migrations, models
import jsonfield.fields
import modelsApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperId', models.AutoField(primary_key=True, serialize=False)),
                ('QIdList', jsonfield.fields.JSONField()),
                ('questionNumberList', jsonfield.fields.JSONField(default=modelsApp.models.JSONdefault1)),
                ('releaseTeacherId', models.IntegerField()),
                ('studentId', models.IntegerField()),
                ('releaseTime', models.DateTimeField(auto_now_add=True)),
                ('submitStartTime', models.DateTimeField(default='2000-01-01 00:00')),
                ('submitEndTime', models.DateTimeField(default='2000-01-01 00:00')),
                ('submitTime', models.DateTimeField(null=True)),
                ('submitAnswerList', jsonfield.fields.JSONField(null=True)),
                ('maxScore', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('submitted', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200)),
                ('questionType', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('knowledgePoint', models.CharField(choices=[('毛泽东思想', '毛泽东思想'), ('新民主主义革命理论', '新民主主义革命理论'), ('社会主义改造理论', '社会主义改造理论'), ('社会主义建设道路初步探索理论成果', '社会主义建设道路初步探索理论成果'), ('邓小平理论', '邓小平理论')], max_length=40)),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('options', jsonfield.fields.JSONField()),
                ('answer', jsonfield.fields.JSONField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'questionslist',
            },
        ),
    ]
