# Generated by Django 3.0.7 on 2020-06-12 11:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('questionType', models.IntegerField()),
                ('knowledgePoint', models.CharField(max_length=20)),
                ('difficulty', models.IntegerField()),
                ('options', jsonfield.fields.JSONField()),
                ('answer', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
