# Generated by Django 3.0.7 on 2020-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionslist',
            name='difficulty',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
