# Generated by Django 3.0.7 on 2020-06-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsApp', '0002_auto_20200617_0006'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionslist',
            table='questionslist',
        ),
    ]
